In [11]:
from tensorflow.keras.models import load_model
from tensorflow.keras import Model
import numpy as np
import json

In [2]:
model = load_model('C:\\Users\\Vignesh\\Desktop\\E-Book Project\\resources\\model\\Model_1.h5')

In [3]:
model.summary()

Model: "model_4"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
books (InputLayer)              [(None, 1)]          0                                            
__________________________________________________________________________________________________
Links (InputLayer)              [(None, 1)]          0                                            
__________________________________________________________________________________________________
book_embedding (Embedding)      (None, 1, 50)        606750      books[0][0]                      
__________________________________________________________________________________________________
link_embedding (Embedding)      (None, 1, 50)        8487900     Links[0][0]                      
____________________________________________________________________________________________

In [4]:
book_layer = model.get_layer('book_embedding')

In [5]:
book_embeddings = book_layer.get_weights()[0]

In [7]:
book_embeddings

array([[-0.0151595 , -0.03291263, -0.10815093, ..., -0.13070813,
        -0.07656811,  0.04940894],
       [-0.05298412, -0.11723048, -0.0116273 , ...,  0.08832487,
        -0.02371714, -0.17221995],
       [ 0.05490308,  0.16668499,  0.00084999, ...,  0.01995222,
        -0.16132703,  0.14861043],
       ...,
       [ 0.06795121,  0.04852963,  0.06763521, ...,  0.04099063,
         0.08118209,  0.11063212],
       [-0.01299005, -0.13907962,  0.08210567, ...,  0.04998609,
         0.25850132,  0.15132734],
       [ 0.09349526,  0.0170656 ,  0.10965734, ..., -0.12552512,
        -0.1107179 , -0.20295493]], dtype=float32)

In [8]:
norm = np.linalg.norm(book_embeddings, axis = 1).reshape(12135, 1)
norm

array([[0.8440084 ],
       [0.85716015],
       [0.76723784],
       ...,
       [0.7436688 ],
       [0.75382674],
       [0.82159454]], dtype=float32)

In [9]:
norm_book_embeddings = book_embeddings / norm

In [10]:
np.sum(np.square(norm_book_embeddings[0])) 

0.99999994

In [20]:
norm_book_embeddings

array([[-0.01796131, -0.03899562, -0.12813964, ..., -0.1548659 ,
        -0.09071961,  0.05854081],
       [-0.06181356, -0.13676614, -0.01356491, ...,  0.10304361,
        -0.02766944, -0.20091921],
       [ 0.0715594 ,  0.21725334,  0.00110786, ...,  0.02600526,
        -0.21026991,  0.19369538],
       ...,
       [ 0.09137294,  0.06525704,  0.09094802, ...,  0.05511947,
         0.10916431,  0.14876531],
       [-0.01723214, -0.18449812,  0.1089185 , ...,  0.06630979,
         0.34291875,  0.20074552],
       [ 0.11379733,  0.02077132,  0.13346893, ..., -0.15278232,
        -0.13475978, -0.24702565]], dtype=float32)

In [21]:
list_embed = norm_book_embeddings.tolist()

In [24]:
file = open('C:\\Users\\Vignesh\\Desktop\\E-Book Project\\resources\\embeddings\\book_embeddings.ndjson', 'w')
file.write(json.dumps(list_embed))

13055170